### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by alangibson01** [sky-uk/cassandra-operator#23]
# Motivation
We would like to determine the future set required to produce a fully functioning stable Cassandra-Operators as version before considering Non Functional Requirements

# Requirements
- define a cassandra cluster using a CRD for a specific version of cassandra and a specific configuration (ideally with the ability to specify number of AZ and number of nodes per AZ)
- app teams to be self-managing their cluster including nodetool actions and repairs
- secured through kubernetes RBAC
- metrics exportable to prometheus
- logs and GC exportable to ELK
- automated backup routine
- manual restore routine 

#  Questions/Key Decisions/Assumptions

### Assumptions
- Built an operator based on Apache cassandra 3.x
- Migration to cassandra as a service will come from clusters on the same version

### Out of Scope
- multi DC
- ability to specify any cassandra versions
- cassandra version upgrade
- auto-registration of clusters to repair (manual registration acceptable for day 1)

# Deliverables
- [x] Create a cassandra image based on phusion image - Parent of #24
- [x] Define clusters through Custom Resource Definitions - Parent of #25 
- [x] Evaluate thelastpickle's cassandra-reaper - Parent of #26
- [x] Ensure operator is aware of clusters it managed after a restart - Parent of #7
- [x] Apply updates on configuration changes - Parent of #8 
- [x] Split CRD bootstrapping out of operator - Parent of #14
- [x] Restart nodes when custom config files are modified - Parent of #5 
- [x] Remove timeout when updating cluster racks - Parent of #19
- [x] Scheduled backups of cluster data - Parent of #20
- [x] Pod liveness and readiness probes frequently start JVMs, consuming CPU - Parent of #30
- [x] Reconcile cluster state based on its definition at regular intervals - Parent of #53 
- [x] Ensure conformity with Kubernetes API conventions -  #33
- [x] Log file system management for cassandra nodes - Parent of #29

**Comment by dudycooly** [comment]
As discussed, we are happy that we have an alpha with listed features above. Hence closing  this and moving all pending items required to mature Alpha from NFR perspective

**Comment by dudycooly** [comment]
# Moved items
- [ ] Test resilience and performance of operator-managed Cassandra clusters - Parent of #41
- [ ] Add mock Jolokia responses to fake-cassandra-docker image - Parent of #32 
- [ ] Explain what will happen if there are multiple operator instances in a given namespace - Parent of #28
- [ ] Provision Last Pickle Reaper alongside each cluster - Parent of #27
