### ISSUE TITLE
Implement NFT for  Cassandra-Operator & its managed clusters

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#41]
## Motivation
- Gain confidence that operator-managed Cassandra clusters have similar underlying resilience and scalability properties than a Cassandra cluster running on VMs
- Prove that operator-managed Clusters have comparable performance to Cassandra clusters on VMs
- Prove that operator-managed Clusters have no impact on other pods running on the same node 
- Implement a resiliency tests for both cassandra-operator & its managed clusters 
- Implement a performance test for both cassandra-operator & its managed clusters 
- Document how performance degrades and what the bottlenecks are 

## Requirements
- Use a test tool that can simulate different load profiles: e.g. write-heavy, read-heavy, both
- Run resiliency and performance test in the `nft` build phase. 
  - Trigger the resiliency simulations while tests are running 
- Record metrics for the operator and its managed clusters via prometheus while test is running
- Deploy an alertmanager and define alerts for both operator and managed-clusters 
- Report success or failure test run based on whether alerts were triggered during the test run

## Deliverables
- [ ]  Define test scenarios, cluster sizes, data model, load profile and queries - see https://github.com/sky-uk/cassandra-operator/issues/41#issuecomment-506028778
- [ ]  Define benchmark to compare performances of operator-managed vs VM clusters - Parent of #155 
- [ ]  Spike cassandra load test tool - Parent of #143 
- [ ]  Record operator and cluster-level metrics in prometheus
  -  e.g. read/write query latencies, timeouts, GC duration, pod resource usage
- [ ]  Define tests failure criteria via alert rules
- [ ]  One-off manual test to check managed-clusters scalability
- [ ]  Automated resiliency tests for operator and managed-clusters (nft tests)
- [ ]  Automated performance load tests for operator and managed clusters (nft tests)
- [ ]  Validate test outcome based on alerts from metrics rather than test output

**Comment by sebbonnet** [comment]
# NFT definition

## Resiliency tests 

A an average load test would be running while the resiliency scenarios are executed once after the other.

### Cluster size and load

TBD how big the cluster under tests should be - this would be in part dictated by the platform we want to run the tests against

### Operator scenarios
- the operator is redeployed
  - why: operator redeployment should not affect cluster operations
  - how: create a cluster definition, delete the operator
- the operator is redeployed during a cluster rolling update
  - why: operator deployment should not affect pending cluster operations
  - how: modify the cluster definition to trigger a rolling update, delete the operator as soon as the first Cassandra node is updated
- the operator is deleted
  - why: managed clusters should be unaffected by operations to their operator 
  - how: covered by above scenarios

### Managed Cassandra cluster scenarios
- a Cassandra pod is deleted
  - why: losing a Cassandra pod should be no different than losing a node in a traditional Cassandra cluster
  - how: run the simulation, delete a Cassandra pod
- a Cassandra process dies
  - why: liveness probe should detect the pod crash and recreate it
  - how: run the simulation, jump onto a Cassandra pod and kill the Cassandra process, we expect the liveness probe to detect this and recreate a new pod.
- a Cassandra pod moves to another node  
  - why: the new pod should rejoin the cluster as the same Cassandra node. The added benefit of moving to another node is to prove that the PV detachment from the old node and the attachment to the new node has no bearing on the Cassandra node identity
  - how: run the simulation, find the target node of a Cassandra pod, mark it as unschedulable and delete the pod - in practice it may not be possible to change the node status when testing in a shared environment, so we should instead add an node anti-affinity rule to the pod.
- a cluster definition change triggers a rolling update
  - why: update operations should be non-disruptive, as the cassandra pods should be updated one at at time
  - how: run the simulation, update a cluster definition to trigger a rolling update
- the number of replicas is increased for a rack
  - why: topology changes should be non-disruptive, as the node should be updated one at at time
  - how: run the simulation, update the cluster definition with an increased rack replica count
- a new rack is added to a cluster definition
  - why: topology changes should be non-disruptive, as the node should be updated one at at time
  - how: run the simulation, update the cluster definition with a new rack

## Performance tests

We want to be able to answer these questions:
- Can an operator managed cluster scale linearly - e.g. add more replicas to handle more load?
- How does the service degrade when a managed-cluster handles too much load? 
  - e.g. slow responses, read/write timeout - are these any different than what we would expect in a traditional Cassandra cluster?
  - identify bottlenecks specific to an operator-managed cluster (if any)
- How does the service degrade when a single operator manage too many clusters? 
  - quantify what is too many clusters for the default deployment 
  - identify bottlenecks - e.g. too many concurrent operations

TBD - What are the NFRs?
- do we have a target cluster size? e.g. small cluster (6 nodes), mid-size cluster (20 nodes), large cluster (50+ nodes)?
- do we have a target TPS / response times?
- what level of error could we tolerate?
- what type of load profile - e.g. heavy read, heavy write, and mixed load?
- would we find it useful to compare the performance of an operator-manged cluster vs a traditional Cassandra cluster running on VMs?

**Comment by adamdougal** [comment]
Closing as no active work has happened on this. We can reopen and update when we start working on it again.
