### ISSUE TITLE
Reconcile cluster state based on its definition at regular intervals

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#53]
### Is your feature request related to a problem? Please describe
There is no reconciliation between the cluster definition and the actual state of the cluster.
This is problematic because:
 - (at best) it could lead to some confusion
 - it could create issues where the next update to the cluster definition cannot modify the cluster as its state is incompatible or will only partially modify the cluster leaving it in an inconsistent state (e.g. configmap updates will not be propagated to manually added rack).
 - Kubernetes resources that are mistakenly deleted would need to be manually recreated, which could be both tedious and prone to error
  - it deviates from the Kubernetes model, where resource definitions are the golden source 
  - updates that fail for whatever reason (e.g. kubernetes apiserver unavailable) are not reapplied, potentially leaving the cluster in an inconsistent state

### Describe the solution you'd like
Move to a model where each Kubernetes resource created by the operator is reconciled with the cluster definition intended state. This would: 
- ensure the cluster definition remains the source of truth and so remains true to the kubernetes philosophy
 - ensure cluster updates that fail for whatever reasons (e.g. kubernetes apiserver unavailable) will eventually be applied, therefore avoiding the need to write complicated retry logic

### Tasks
- [x] Introduce reconciliation hook via controller-runtime based controller - #150
  - leftovers of #150: refactor stuff out of cmd package, remove duplicate status.go and operator.go, fix logs timestamp, confirm RBAC changes to allow watch for secrets and pods, configmaps watch already allowed and to allow update on cassandra - #175
- [x] Add reconciliation logic for changes while operator is down - #171
- [x] Add reconciliation logic for changes that were partially applied - #171 
- [x] Add reconciliation logic for manually changes to resources managed by the operator - #171 
- [x] Add reconciliation logic for headless service changes - #171 
- [x] Expose reconciliation syncPeriod as cmd line arg - #172
- ~Make it possible to pause the reconciliation~ - descope, as it's not clear what scenario would benefit from this

**Comment by sebbonnet** [comment]
We want the reconciliation to recover from cases where changes were not applied (e.g. apiserver down) or while the operator was down.

**Use Cases**
While the operator down:
- cluster is added / deleted
- replica is added
- rack is added
- pod properties (e.g. mem, cpu, probes) are modified
- snapshot is added / removed / modified
- snapshot cleanup is added / removed / modified
- configmap is added / removed / modified

We also need to cover cases where the changes were partially applied, for instance:
- a cluster rack could not be added
- a rack properties change (e.g. mem, cpu) could not be applied
- configmap changes were not rolled out to one rack

Resources managed by the operator may be manually created or intentionally deleted or changed
- a statefulset is manually ~added~ / deleted 
- a statefulset is edited and a replica removed, a replica added or other properties changed 
- a snapshot cronjob is manually deleted / updated / added
- a snapshot cleanup cronjob is manually deleted / updated / added
- ~a pvc is deleted~ out of scope
- ~a pv is deleted~ out of scope
- the headless service is deleted

**Out of scope**
- changes resources not directly managed by the operator such as pods, pvc and pvs, rbac
- changes applied to resources that have not been labelled with the operator label
- scaling down a statefulset that was manually added, deferred until we support scale down

**Implementation**
In terms of implementation, I think we can keep most of the existing reconciliation logic in the `receiver.go`
by making the reconciler controller build a v1alpha1.Cassandra{} representing the current state.
This would make a clean separation with the controller responsible for determining current and desired state, while the receiver would continue to determine and apply the delta.
This should handle most of the cases above, except the creation of the headless service in case it is deleted - but we can tackle this separately.

**Testing**
In terms of testing, we should validate via unit tests that the reconciler is able to rebuild the current state for the various scenarios. We should also add one e2e for each group of scenarios:
- a cluster definition is changed while the operator is down
- a change was applied partially
- a resource managed by the operator is deleted

**Comment by sebbonnet** [comment]
All sub-tasks complete
